// Generated by SaltoExternalIdService
trigger Pricebook2SaltoIdTrigger on Pricebook2 (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}