// Generated by SaltoExternalIdService
trigger SBQQCostSaltoIdTrigger on SBQQ__Cost__c (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}