// Generated by SaltoExternalIdService
trigger SBQQQuoteTemplateSaltoIdTrigger on SBQQ__QuoteTemplate__c (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}