// Generated by SaltoExternalIdService
trigger SBQQLineColumnSaltoIdTrigger on SBQQ__LineColumn__c (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}