// Generated by SaltoExternalIdService
trigger SBQQProductOptionSaltoIdTrigger on SBQQ__ProductOption__c (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}