// Generated by SaltoExternalIdService
trigger SBQQPriceConditionSaltoIdTrigger on SBQQ__PriceCondition__c (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}