// Generated by SaltoExternalIdService
trigger SBQQCustomActionSaltoIdTrigger on SBQQ__CustomAction__c (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}