// Generated by SaltoExternalIdService
trigger SBQQRelatedContentSaltoIdTrigger on SBQQ__RelatedContent__c (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}