// Generated by SaltoExternalIdService
trigger SBQQErrorConditionSaltoIdTrigger on SBQQ__ErrorCondition__c (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}