// Generated by SaltoExternalIdService
trigger SBQQPriceActionSaltoIdTrigger on SBQQ__PriceAction__c (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}