// Generated by SaltoExternalIdService
trigger SBQQQuoteTermSaltoIdTrigger on SBQQ__QuoteTerm__c (after insert) {
    new SaltoExternalIdService.Builder().withFieldDeveloperName('ExtId').build().updateSaltoId(Trigger.new);
}